repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
    -   id: commitizen
        stages: [commit-msg]

-   repo: https://github.com/golangci/golangci-lint
    rev: v2.1.2
    hooks:
    -   id: golangci-lint
        args: [--timeout=5m]

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
    -   id: gitleaks
